spring:
    datasource:
        username: root
        password: 1234
        url: jdbc:mysql://localhost:3306/peliculas
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

